### ISSUE TITLE
Possible to go from auto-value object back to a cursor via ContentValues?

### ISSUE THREAD

**Issue by laurencedawson** [gabrielittner/auto-value-cursor#14]
Hi,
I've just started using the lib and was wondering if it's possible to take an auto-value object and essentially perform the opposite of this library? 

Would make working with cursors that one step easier!

Cheers

**Comment by gabrielittner** [comment]
Yes it is possible.

It would even be possible to generate a ContentValues Builder class similar [AutoValue Builders](https://github.com/google/auto/tree/master/value#builders) for ContentValues. Something like this:

```java
@AutoValue public abstract class User {
  abstract String id();
  abstract String name();
  abstract String email();

  @ContentValuesBuilder
  abstract static class ContentValuesBuilder {
    abstract Builder id(String id);
    abstract Builder name(String name);
    abstract Builder email(String email);
    abstract ContentValues build();
  }

  // returns ContentValuesBuilder with values from current object
  abstract ContentValuesBuilder toContentValuesBuilder();

  public static User create(Cursor cursor) {
    return AutoValue_User.createFromCursor(cursor);
  }
}

**Comment by rharter** [comment]
The idea of a `ContentValuesBuilder` might be simplified by simply adding a `toContentValues()` method to the generated class, so you could use it like this:

```java
ContentValues values = User.builder()
  .id(id)
  .name(name)
  .email(email)
  .build()
  .toContentValues();
```

The `@ContentValuesBuilder` seems inflexible in that the user would have to add both `Builder` and `ContentValuesBuilder` inner classes in order to use it.  I wonder if the `auto-value-cursor` generated class could simply override the `$AutoValue_User.Builder` class to add a `public ContentValues asContentValues()` method so that, if the class has an `@AutoValue.Builder` inner class, the ContentValues addition can be added with no extra code.

My suspicion is the the extension support in AutoValue will have to be extended to the Builder in order to accommodate this type of functionality.

**Comment by rharter** [comment]
Re: the `toContentValues` method, you could simply check the class for an abstract method returning `ContentValues`, and implement that to convert the class to `ContentValues` and return it.

**Comment by gabrielittner** [comment]
Yeah a regular `toContentValues()` should definitely be done and is super easy to implement. 
I just thought that it might be nice to have the `ContentValuesBuilder` on top of that. One major advantage of having it would be that you can use it for partial updates like only updating name and email. That would only work with either a separate Builder or extending the default Builder, because `build().toContentValues()` would do null checks.

**Comment by gabrielittner** [comment]
@laurencedawson The latest `0.3.0-SNAPSHOT` will now generate a `toContentValues()` if you add an abstract one to your class.

**Comment by laurencedawson** [comment]
@gabrielittner Fantastic thanks!

**Comment by laurencedawson** [comment]
@gabrielittner sorry but can you provide a quick example? Thanks

**Comment by gabrielittner** [comment]
You just need to change the dependency to the snapshot version and add
`public abstract ContentValues toContentValues()` to your AutoValue class.

**Comment by gabrielittner** [comment]
You just need to change the dependency to the snapshot version and add `public abstract ContentValues toContentValues()` to your AutoValue class.

**Comment by laurencedawson** [comment]
Have you published the snapshot or do you mean built it and add locally?

**Comment by gabrielittner** [comment]
Snapshots are published to a different repository. You have to add
```groovy
maven {
    url "https://oss.sonatype.org/content/repositories/snapshot"
}
```
to the repositories block in your build.gradle file.

**Comment by laurencedawson** [comment]
Aha thanks!

**Comment by laurencedawson** [comment]
Can confirm this is working great. Thanks again for your help.

**Comment by laurencedawson** [comment]
I created [another issue](https://github.com/gabrielittner/auto-value-cursor/issues/24) but I think it's probably best discussed in here.

If a custom class is defined and setup with the @CursorAdapter annotation, the toContentValues method will cause the build to fail throwing the following error message:

`Error:Property "Y" has type "X" that can't be put into ContentValues`

Would it be possible to add along side the CursorAdapterFactory (containing createFromCursor) a method to saveToCursorValues?

Thanks

**Comment by gabrielittner** [comment]
I'll add support for that, but I'm currently a bit busy. Maybe this or next weekend. If you want to give it a try before that I'm happy about pull requests :smile:
