### ISSUE TITLE
Consider putNull support for foreign key ID values

### ISSUE THREAD

**Issue by mtiidla** [gabrielittner/auto-value-cursor#26]
This should be similar to #24 and #25 

When using foreign keys you can't put 0 as an ID value and need to use putNull instead. 
Current workaround would be providing another contentValues method as described in the comments of #25 

```
abstract ContentValues toCompleteContentValues();

public ContentValues toContentValues() {
	ContentValues contentValues = toCompleteContentValues();
	contentValues.remove(TableEvent.COLUMN_ID);
	if (subjectId() == 0) {
		contentValues.putNull(TableEvent.COLUMN_SUBJECT_ID);
	}
	return contentValues;
}
```

**Comment by gabrielittner** [comment]
You can use the new `@ValuesAdapter` annotation for custom types in `0.4.0-SNAPSHOT` to ignore fields when creating `ContentValues`. I don't want to support this directly because others might use a different value that should be translated to `null` like -1.

```java
public final class ForeignKeyAdapter {
  public static ContentValues ignoreField(int subjectId) {
    ContentValues contentValues = new ContentValues(1);
    if (subjectId == 0) {
        contentValues.putNull(TableEvent.COLUMN_SUBJECT_ID);
    } else {
        contentValues.put(TableEvent.COLUMN_SUBJECT_ID, subjectId);
    }
    return contentValues;
  }
}
```

```java
@AutoValue public abstract class ValueClass {
  @ValuesAdapter(ForeignKeyAdapter.class) abstract int subjectId();
}
```

As an alternative when #29 is implemented you could change your `subjectId` field to be `@Nullable Integer` and use `null` instead of 0.
